# config/routes.yaml
about_me:
    path: /pages/about_me
    controller: App\Controller\AboutMeController::aboutMePage

updateAll:
    path: /pages/about_me/updateAll
    controller: App\Controller\AboutMeController::updateAllHobbies

updateOne:
    path: /pages/about_me/updateOne
    controller: App\Controller\AboutMeController::updateOneHobby