# config/routes.yaml
main:
    path: /
    controller: App\Controller\AboutMeController::simple_answer

about:
    path: /pages/first
    controller: App\Controller\AboutMeController::about

about_me:
    path: /pages/about_me
    controller: App\Controller\AboutMeController::aboutMePage



