doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Module\AboutMe:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/about_me'
                prefix: 'App\Modules\AboutMe'
                alias: AboutMe